'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'
import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { ChartNoAxesCombined, Crown, Gauge, Scale, Timer } from 'lucide-react'
import toast from 'react-hot-toast'
import { createClient } from '@/lib/supabase/client'

const money = value => `\u20B9${Number(value || 0).toLocaleString('en-IN')}`
const key = value => { const date = new Date(value); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}` }
const label = value => new Intl.DateTimeFormat('en-IN', { month: 'short' }).format(new Date(Number(value.slice(0, 4)), Number(value.slice(5)) - 1, 1))
const won = status => /won|allowed|granted|favour/i.test(status || '')
const lost = status => /lost|dismissed|rejected|against/i.test(status || '')
const closed = status => /closed|disposed|judgment received|won|lost|dismissed|rejected/i.test(status || '')

export default function AdvancedAnalytics() {
  const [cases, setCases] = useState([]); const [bills, setBills] = useState([]); const [paid, setPaid] = useState(false); const [loading, setLoading] = useState(true)
  const load = useCallback(async () => { const supabase = createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) return setLoading(false); const { data: advocate } = await supabase.from('advocates').select('id').eq('user_id', user.id).single(); if (!advocate) return setLoading(false); const [caseResult, billResult, planResult] = await Promise.all([supabase.from('cases').select('id, case_type, judge_name, status, created_at, updated_at').eq('advocate_id', advocate.id), supabase.from('billing').select('fee_amount, fee_status, paid_date, created_at, cases(case_type)'), supabase.from('advocate_subscriptions').select('plan, status, expires_at').eq('advocate_id', advocate.id).maybeSingle()]); if (caseResult.error) toast.error(caseResult.error.message); setCases(caseResult.data || []); setBills(billResult.data || []); const active = ['analytics_monthly', 'pro_monthly'].includes(planResult.data?.plan || '') && planResult.data?.status === 'active' && (!planResult.data?.expires_at || new Date(planResult.data.expires_at) > new Date()); setPaid(Boolean(active)); setLoading(false) }, [])
  useEffect(() => { const timer = window.setTimeout(() => { void load() }, 0); return () => window.clearTimeout(timer) }, [load])
  const report = useMemo(() => { const months = [...Array(6)].map((_, index) => { const date = new Date(); date.setMonth(date.getMonth() - (5 - index), 1); return key(date) }); const success = months.map(month => { const decided = cases.filter(item => key(item.updated_at) === month && (won(item.status) || lost(item.status))); const wonCount = decided.filter(item => won(item.status)).length; return { month: label(month), successRate: decided.length ? Math.round(wonCount / decided.length * 100) : 0, decided: decided.length } }); const revenueTypes = Object.values(bills.filter(bill => bill.fee_status === 'Paid').reduce((groups, bill) => { const type = bill.cases?.case_type || 'Other'; groups[type] = (groups[type] || 0) + Number(bill.fee_amount || 0); return groups }, {})).map((amount, index) => ({ type: Object.keys(bills.filter(bill => bill.fee_status === 'Paid').reduce((groups, bill) => { groups[bill.cases?.case_type || 'Other'] = true; return groups }, {}))[index], revenue: amount })); const judge = Object.values(cases.reduce((groups, item) => { const name = item.judge_name || 'Not recorded'; if (!groups[name]) groups[name] = { judge: name, won: 0, lost: 0 }; if (won(item.status)) groups[name].won += 1; if (lost(item.status)) groups[name].lost += 1; return groups }, {})).map(item => ({ ...item, successRate: item.won + item.lost ? Math.round(item.won / (item.won + item.lost) * 100) : 0 })); const durations = cases.filter(item => closed(item.status)).map(item => Math.max(1, (new Date(item.updated_at) - new Date(item.created_at)) / 86400000)); const averageDays = durations.length ? Math.round(durations.reduce((a, b) => a + b, 0) / durations.length) : 0; const recentRevenue = bills.filter(bill => bill.fee_status === 'Paid' && key(bill.paid_date || bill.created_at) === months[5]).reduce((sum, bill) => sum + Number(bill.fee_amount || 0), 0); const pastRevenue = bills.filter(bill => bill.fee_status === 'Paid' && months.includes(key(bill.paid_date || bill.created_at))).reduce((sum, bill) => sum + Number(bill.fee_amount || 0), 0); return { success, revenueTypes, judge, averageDays, predictedRevenue: Math.round(pastRevenue / 6), recentRevenue } }, [bills, cases])
  if (loading) return <div className="h-48 animate-pulse rounded-2xl bg-slate-100" />
  if (!paid) return <div className="mx-auto max-w-5xl rounded-3xl bg-gradient-to-br from-slate-950 to-blue-950 p-8 text-white shadow-xl"><Crown className="h-10 w-10 text-amber-300" /><h1 className="mt-4 text-2xl font-bold">Advanced Analytics</h1><p className="mt-2 max-w-xl text-sm leading-6 text-slate-200">Six-month trends, revenue by case type, your recorded outcomes by judge and time-based projections.</p><p className="mt-5 text-3xl font-bold">₹300 <span className="text-base font-medium text-slate-300">/ month</span></p><p className="mt-3 text-xs text-slate-300">Payment activation will be connected before this feature is sold.</p></div>
  return <div className="mx-auto max-w-6xl"><div><h1 className="flex items-center gap-2 text-2xl font-bold text-slate-900"><ChartNoAxesCombined className="h-6 w-6 text-blue-600" />Advanced Analytics</h1><p className="mt-1 text-sm text-slate-500">Your practice data, aggregated from saved case and billing records.</p></div><div className="mt-6 grid gap-4 sm:grid-cols-3"><Metric icon={Gauge} label="Projected monthly revenue" value={money(report.predictedRevenue)} /><Metric icon={Timer} label="Average closed-case duration" value={report.averageDays ? `${report.averageDays} days` : 'No closed cases'} /><Metric icon={Scale} label="Current-month revenue" value={money(report.recentRevenue)} /></div><div className="mt-6 grid gap-6 lg:grid-cols-2"><Chart title="Success-rate trend (6 months)"><ResponsiveContainer width="100%" height={270}><LineChart data={report.success}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="month" /><YAxis unit="%" domain={[0, 100]} /><Tooltip /><Line type="monotone" dataKey="successRate" stroke="#2563eb" strokeWidth={3} /></LineChart></ResponsiveContainer></Chart><Chart title="Revenue by case type"><ResponsiveContainer width="100%" height={270}><BarChart data={report.revenueTypes}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="type" /><YAxis tickFormatter={value => `\u20B9${value}`} /><Tooltip formatter={value => money(value)} /><Bar dataKey="revenue" fill="#16a34a" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer></Chart><Chart title="Your recorded outcomes by judge"><ResponsiveContainer width="100%" height={270}><BarChart data={report.judge}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="judge" hide /><YAxis unit="%" domain={[0, 100]} /><Tooltip /><Legend /><Bar dataKey="successRate" name="Success rate" fill="#9333ea" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer><p className="mt-2 text-xs text-slate-400">Based only on your recorded case statuses; not a rating or prediction of any judge.</p></Chart><Chart title="Time analysis"><div className="flex h-[270px] items-center justify-center text-center"><div><p className="text-5xl font-bold text-slate-900">{report.averageDays || '—'}</p><p className="mt-2 text-sm text-slate-500">Average days from case creation to recorded closure</p></div></div></Chart></div><p className="mt-6 rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs leading-5 text-amber-900">Predictions are simple averages from your historical records. They are planning estimates only—not legal outcome, revenue, or court-timeline guarantees.</p></div>
}
function Metric({ icon: Icon, label, value }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><Icon className="h-6 w-6 text-blue-600" /><p className="mt-3 text-sm text-slate-500">{label}</p><p className="mt-1 text-xl font-bold text-slate-900">{value}</p></div> }
function Chart({ title, children }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-3 font-bold text-slate-900">{title}</h2>{children}</section> }
