'use client'

import { useCallback, useEffect, useState } from 'react'
import { BrainCircuit, Crown, ShieldAlert, Sparkles } from 'lucide-react'
import toast from 'react-hot-toast'
import { createClient } from '@/lib/supabase/client'

export default function CaseStrategy() {
  const [cases, setCases] = useState([]); const [caseId, setCaseId] = useState(''); const [paid, setPaid] = useState(false); const [loading, setLoading] = useState(true); const [generating, setGenerating] = useState(false); const [strategy, setStrategy] = useState(null)
  const load = useCallback(async () => { const supabase = createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) return setLoading(false); const { data: advocate } = await supabase.from('advocates').select('id').eq('user_id', user.id).single(); if (!advocate) return setLoading(false); const [caseResult, planResult] = await Promise.all([supabase.from('cases').select('id, case_number, case_title').eq('advocate_id', advocate.id).order('created_at', { ascending: false }), supabase.from('advocate_subscriptions').select('plan, status, expires_at').eq('advocate_id', advocate.id).maybeSingle()]); setCases(caseResult.data || []); setCaseId(caseResult.data?.[0]?.id || ''); const active = planResult.data?.plan === 'strategy_monthly' && planResult.data.status === 'active' && (!planResult.data.expires_at || new Date(planResult.data.expires_at) > new Date()); setPaid(Boolean(active)); setLoading(false) }, [])
  useEffect(() => { const timer = window.setTimeout(() => { void load() }, 0); return () => window.clearTimeout(timer) }, [load])
  const generate = async () => { if (!caseId) return; setGenerating(true); try { const response = await fetch('/api/case-strategy', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ caseId }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Could not generate strategy.'); setStrategy(data.strategy); toast.success('Case strategy generated for advocate review.'); } catch (error) { toast.error(error instanceof Error ? error.message : 'Could not generate strategy.') } finally { setGenerating(false) } }
  if (loading) return <div className="h-48 animate-pulse rounded-2xl bg-slate-100" />
  return <div className="mx-auto max-w-4xl"><div><h1 className="flex items-center gap-2 text-2xl font-bold text-slate-900"><BrainCircuit className="h-6 w-6 text-violet-600" />Case Strategy</h1><p className="mt-1 text-sm text-slate-500">AI-assisted preparation notes. Advocate review is always required.</p></div>{!paid ? <section className="mt-6 rounded-3xl bg-gradient-to-br from-violet-950 to-indigo-900 p-7 text-white shadow-xl"><Crown className="h-9 w-9 text-amber-300" /><h2 className="mt-4 text-2xl font-bold">Case Strategy Pro</h2><p className="mt-2 max-w-xl text-sm leading-6 text-violet-100">Generate structured preparation notes, risk factors and next steps for each matter.</p><p className="mt-5 text-3xl font-bold">₹300 <span className="text-base font-medium text-violet-200">/ month</span></p><p className="mt-3 text-xs text-violet-200">Payment activation will be connected before this feature is sold.</p></section> : <><section className="mt-6 rounded-2xl border border-violet-200 bg-violet-50 p-5"><label className="text-sm font-bold text-violet-950">Select case</label><select value={caseId} onChange={event => setCaseId(event.target.value)} className="mt-2 w-full rounded-xl border border-violet-200 bg-white px-3 py-3 text-sm">{cases.map(item => <option key={item.id} value={item.id}>{item.case_number} - {item.case_title || 'Untitled case'}</option>)}</select><button type="button" disabled={generating || !caseId} onClick={generate} className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-violet-600 py-3 font-bold text-white disabled:opacity-60"><Sparkles className="h-4 w-4" />{generating ? 'Generating strategy...' : 'Generate case strategy'}</button></section>{strategy && <section className="mt-6 space-y-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-bold text-slate-900">Strategy summary</h2><span className="rounded-full bg-blue-100 px-3 py-1 text-sm font-bold text-blue-700">Success probability: {strategy.successProbability}%</span></div><p className="text-sm leading-6 text-slate-700">{strategy.strategySummary}</p><div className="grid gap-5 sm:grid-cols-2"><List title="Risk factors" items={strategy.riskFactors} tone="red" /><List title="Suggested next steps" items={strategy.nextSteps} tone="blue" /></div><p className="flex gap-2 rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs leading-5 text-amber-900"><ShieldAlert className="h-4 w-4 shrink-0" />{strategy.reviewNotice || 'AI-generated preparation notes only. Verify all facts, law, limitation periods and court practice before acting.'}</p></section>}</>}</div>
}
function List({ title, items = [], tone }) { return <div className={`rounded-xl p-4 ${tone === 'red' ? 'bg-red-50' : 'bg-blue-50'}`}><h3 className="font-bold text-slate-900">{title}</h3><ul className="mt-3 space-y-2 text-sm text-slate-700">{items.map((item, index) => <li key={index}>• {item}</li>)}</ul></div> }
