'use client'

import { useCallback, useEffect, useState } from 'react'
import { FileSearch, ShieldAlert, Sparkles, UploadCloud } from 'lucide-react'
import toast from 'react-hot-toast'
import { createClient } from '@/lib/supabase/client'

export default function DocumentOcr() {
  const [cases, setCases] = useState([]); const [caseId, setCaseId] = useState(''); const [paid, setPaid] = useState(false); const [file, setFile] = useState(null); const [loading, setLoading] = useState(true); const [processing, setProcessing] = useState(false); const [result, setResult] = useState(null)
  const load = useCallback(async () => { const supabase = createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) return setLoading(false); const { data: advocate } = await supabase.from('advocates').select('id').eq('user_id', user.id).single(); if (!advocate) return setLoading(false); const [caseResult, planResult] = await Promise.all([supabase.from('cases').select('id, case_number, case_title').eq('advocate_id', advocate.id).order('created_at', { ascending: false }), supabase.from('advocate_subscriptions').select('plan, status, expires_at').eq('advocate_id', advocate.id).maybeSingle()]); setCases(caseResult.data || []); setCaseId(caseResult.data?.[0]?.id || ''); const active = ['ocr_monthly', 'pro_monthly'].includes(planResult.data?.plan || '') && planResult.data?.status === 'active' && (!planResult.data?.expires_at || new Date(planResult.data.expires_at) > new Date()); setPaid(Boolean(active)); setLoading(false) }, [])
  useEffect(() => { const timer = window.setTimeout(() => { void load() }, 0); return () => window.clearTimeout(timer) }, [load])
  const extract = async () => { if (!file || !caseId) return toast.error('Select a case and court order file.'); setProcessing(true); try { const form = new FormData(); form.append('caseId', caseId); form.append('file', file); const response = await fetch('/api/document-ocr', { method: 'POST', body: form }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'OCR failed.'); setResult(data.extraction); toast.success('Order details extracted. Review before applying.'); } catch (error) { toast.error(error instanceof Error ? error.message : 'OCR failed.') } finally { setProcessing(false) } }
  const apply = async () => { try { const response = await fetch('/api/document-ocr', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ caseId, extraction: result }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Could not apply results.'); toast.success('Reviewed OCR details applied to this case.'); } catch (error) { toast.error(error instanceof Error ? error.message : 'Apply failed.') } }
  if (loading) return <div className="h-48 animate-pulse rounded-2xl bg-slate-100" />
  if (!paid) return <div className="mx-auto max-w-4xl rounded-3xl bg-gradient-to-br from-indigo-950 to-slate-950 p-8 text-white shadow-xl"><FileSearch className="h-10 w-10 text-amber-300" /><h1 className="mt-4 text-2xl font-bold">Court Order OCR</h1><p className="mt-2 max-w-xl text-sm leading-6 text-slate-200">Extract dates, judge, status, orders and action items from a court order photo or PDF.</p><p className="mt-5 text-3xl font-bold">₹200 <span className="text-base font-medium text-slate-300">/ month</span></p><p className="mt-3 text-xs text-slate-300">Payment activation will be connected before this feature is sold.</p></div>
  return <div className="mx-auto max-w-4xl"><div><h1 className="flex items-center gap-2 text-2xl font-bold text-slate-900"><FileSearch className="h-6 w-6 text-indigo-600" />Court Order OCR</h1><p className="mt-1 text-sm text-slate-500">Upload a PDF or photo and review AI-extracted details before updating your case.</p></div><section className="mt-6 rounded-2xl border border-indigo-100 bg-indigo-50 p-5"><select value={caseId} onChange={event => setCaseId(event.target.value)} className="w-full rounded-xl border border-indigo-200 bg-white px-3 py-3 text-sm">{cases.map(item => <option key={item.id} value={item.id}>{item.case_number} - {item.case_title || 'Untitled case'}</option>)}</select><label className="mt-4 flex cursor-pointer items-center justify-center gap-2 rounded-xl border-2 border-dashed border-indigo-200 bg-white px-4 py-9 text-sm font-bold text-indigo-700"><UploadCloud className="h-5 w-5" />{file ? file.name : 'Choose court order (PDF / photo)'}<input type="file" accept="application/pdf,image/jpeg,image/png,image/webp" className="hidden" onChange={event => setFile(event.target.files?.[0] || null)} /></label><button type="button" disabled={processing || !file} onClick={extract} className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-indigo-600 py-3 font-bold text-white disabled:opacity-60"><Sparkles className="h-4 w-4" />{processing ? 'Reading court order...' : 'Extract case details'}</button></section>{result && <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-bold text-slate-900">Review extracted details</h2><span className="rounded-full bg-blue-100 px-3 py-1 text-sm font-bold text-blue-700">Confidence: {result.confidence}%</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Info label="Order date" value={result.orderDate} /><Info label="Next date" value={result.nextDate} /><Info label="Judge" value={result.judgeName} /><Info label="Status" value={result.status} /></div><List title="Orders" items={result.orders} /><List title="Action items" items={result.actionItems?.map(item => `${item.title}${item.dueDate ? ` — ${item.dueDate}` : ''}`)} /><p className="mt-5 flex gap-2 rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs leading-5 text-amber-900"><ShieldAlert className="h-4 w-4 shrink-0" />{result.reviewNotice || 'Verify every extracted field against the original order before applying.'}</p><button type="button" onClick={apply} className="mt-4 w-full rounded-xl bg-emerald-600 py-3 font-bold text-white">Apply reviewed details to case</button></section>}</div>
}
function Info({ label, value }) { return <div className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-sm font-bold text-slate-900">{value || 'Not extracted'}</p></div> }
function List({ title, items = [] }) { return <div className="mt-5"><h3 className="font-bold text-slate-900">{title}</h3><ul className="mt-2 space-y-2 text-sm text-slate-700">{items?.length ? items.map((item, index) => <li key={index} className="rounded-lg bg-slate-50 p-3">• {item}</li>) : <li className="text-slate-500">None extracted.</li>}</ul></div> }
