'use client'

import { useEffect, useState } from 'react'
import { BellRing, Volume2 } from 'lucide-react'
import toast from 'react-hot-toast'
import { createClient } from '@/lib/supabase/client'
import { useNotifications } from '@/src/hooks/useNotifications'

const DEFAULTS = { reminders_enabled: true, case_updates_enabled: true, client_messages_enabled: true, urgent_enabled: true, sound_enabled: true, vibration_enabled: true, quiet_start: '22:00', quiet_end: '07:00' }

export default function NotificationPreferencePanel() {
  const { permission, requestPermission } = useNotifications(); const [preferences, setPreferences] = useState(DEFAULTS); const [saving, setSaving] = useState(false)
  useEffect(() => { async function load() { const supabase = createClient(); const { data: { session } } = await supabase.auth.getSession(); if (!session?.user) return; const { data } = await supabase.from('notification_preferences').select('*').eq('user_id', session.user.id).maybeSingle(); if (data) setPreferences(current => ({ ...current, ...data })) } load() }, [])
  async function save() { setSaving(true); try { const supabase = createClient(); const { data: { session } } = await supabase.auth.getSession(); if (!session?.user) throw new Error('Please sign in first'); const { error } = await supabase.from('notification_preferences').upsert({ user_id: session.user.id, ...preferences, updated_at: new Date().toISOString() }); if (error) throw error; toast.success('Notification preferences saved') } catch (error) { toast.error(error instanceof Error ? error.message : 'Could not save preferences') } finally { setSaving(false) } }
  return <section className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><BellRing className="h-5 w-5 text-blue-600" /><h2 className="font-bold text-gray-900">Notification Preferences</h2></div><p className="mt-1 text-sm text-gray-500">Choose which alerts you want to receive.</p><button type="button" onClick={() => requestPermission().catch(error => toast.error(error.message))} className="mt-4 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-bold text-white">{permission === 'granted' ? 'Push enabled on this device' : 'Enable phone notifications'}</button><div className="mt-5 grid gap-3 sm:grid-cols-2">{[['reminders_enabled', 'Deadline reminders'], ['case_updates_enabled', 'Case status updates'], ['client_messages_enabled', 'Client message alerts'], ['urgent_enabled', 'Urgent alerts'], ['sound_enabled', 'Sound'], ['vibration_enabled', 'Vibration']].map(([key, label]) => <label key={key} className="flex items-center justify-between rounded-xl border border-gray-100 p-3 text-sm font-semibold text-gray-700"><span>{key === 'sound_enabled' && <Volume2 className="mr-1 inline h-4 w-4" />}{label}</span><input type="checkbox" checked={preferences[key]} onChange={event => setPreferences(current => ({ ...current, [key]: event.target.checked }))} className="h-4 w-4" /></label>)}</div><div className="mt-4 grid grid-cols-2 gap-3"><label className="text-sm font-semibold text-gray-700">Quiet hours start<input type="time" value={preferences.quiet_start} onChange={event => setPreferences(current => ({ ...current, quiet_start: event.target.value }))} className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2" /></label><label className="text-sm font-semibold text-gray-700">Quiet hours end<input type="time" value={preferences.quiet_end} onChange={event => setPreferences(current => ({ ...current, quiet_end: event.target.value }))} className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2" /></label></div><button type="button" onClick={save} disabled={saving} className="mt-5 w-full rounded-xl border border-blue-200 bg-blue-50 px-4 py-3 font-bold text-blue-700">{saving ? 'Saving...' : 'Save preferences'}</button></section>
}
